//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public long Id { get; set; }
        public int TenantId { get; set; }
        public long MachineId { get; set; }
        public string MachineCode { get; set; }
        public string Code { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public decimal Duration { get; set; }
        public string Memo { get; set; }
        public string ObjectId { get; set; }
    }
}
